ls:
  .css: kebab-case
  .js: kebab-case
  .json: kebab-case
  .md: SCREAMING_SNAKE_CASE
  .php: snake_case
  .sh: kebab-case
  .sql: snake_case
  .svg: kebab-case
  .txt: snake_case

  tests:
    .php: PascalCase
    .spec.js: kebab-case
    .test.js: kebab-case

ignore:
  - .idea
  - .vscode
  - node_modules
  - src/third_party
  - test-results
  - tmp
  - vendor
