# Homebrew dev packages
brew "bash"
brew "coreutils"
brew "file"
brew "gifsicle"
brew "hadolint"
brew "icu4c", link: true
brew "jpeginfo"
brew "jpegoptim"
brew "jq"
brew "mdbtools"
brew "nodejs"
brew "npm"
brew "openjdk@17"
brew "oxipng"
brew "php"
brew "pngcheck"
brew "pngquant"
brew "sevenzip"
brew "shellcheck"
brew "shfmt"
brew "tidy-html5"
brew "unzip"
brew "webp"
brew "xmlstarlet"
brew "yamllint"
