# Homebrew dev packages
brew "coreutils"
brew "curl"
brew "git"
brew "hadolint"
brew "mdbtools"
brew "nodejs"
brew "npm"
brew "openjdk"
brew "php"
brew "sevenzip"
brew "shellcheck"
brew "shfmt"
brew "tidy-html5"
