import globals from "globals";
import js from "@eslint/js";
import n from "eslint-plugin-n";
import promise from "eslint-plugin-promise";
import regexp from "eslint-plugin-regexp";
import unicorn from "eslint-plugin-unicorn";

export default [
  js.configs.recommended,
  regexp.configs["flat/recommended"],
  promise.configs["flat/recommended"],
  unicorn.configs.recommended,
  {
    rules: {
      "array-callback-return": "error",
      "arrow-body-style": "error",
      "camelcase": "error",
      "class-methods-use-this": "error",
      "consistent-this": "error",
      "curly": "error",
      "default-case": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      "eqeqeq": "error",
      "func-style": "error",
      "grouped-accessor-pairs": "error",
      "guard-for-in": "error",
      "max-nested-callbacks": "error",
      "max-params": "error",
      "new-cap": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-bitwise": "error",
      "no-caller": "error",
      "no-constructor-return": "error",
      "no-div-regex": "error",
      "no-duplicate-imports": "error",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-eq-null": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-inner-declarations": "error",
      "no-invalid-this": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-multi-str": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-wrappers": "error",
      "no-object-constructor": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow": "error",
      "no-throw-literal": "error",
      "no-undef-init": "error",
      "no-undefined": "error",
      "no-underscore-dangle": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-unused-expressions": "error",
      "no-use-before-define": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-void": "error",
      "object-shorthand": "error",
      "one-var": ["error", "never"],
      "operator-assignment": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "promise/prefer-await-to-then": "error",
      "radix": "error",
      "sort-imports": ["error", { allowSeparatedGroups: true }],
      "regexp/prefer-named-capture-group": "error",
      "require-await": "error",
      "require-unicode-regexp": "error",
      "sort-vars": "error",
      "spaced-comment": "error",
      "strict": ["error", "never"],
      "symbol-description": "error",
      "unicode-bom": "error",
      "unicorn/better-regex": "error",
      "unicorn/consistent-destructuring": "error",
      "unicorn/custom-error-definition": "error",
      "unicorn/no-keyword-prefix": "error",
      "unicorn/no-null": "off",
      "unicorn/no-typeof-undefined": "off",
      "unicorn/numeric-separators-style": "off",
      "yoda": "error",
    },
  },
  {
    ...n.configs["flat/recommended-module"],
    files: ["*.js", "scripts/**", "tests/**"],
    languageOptions: {
      ...n.configs["flat/recommended-module"].languageOptions,
      globals: { ...globals.node },
    },
    rules: {
      ...n.configs["flat/recommended-module"].rules,
      "n/hashbang": ["error", { additionalExecutables: ["scripts/**/*.js"] }],
      "n/no-path-concat": "error",
      "n/no-process-exit": "off",
      "n/no-unsupported-features/node-builtins": "off",
      "n/prefer-global/buffer": ["error", "never"],
      "n/prefer-global/console": ["error", "never"],
      "n/prefer-global/process": ["error", "never"],
      "n/prefer-global/text-decoder": ["error", "never"],
      "n/prefer-global/text-encoder": ["error", "never"],
      "n/prefer-promises/fs": "error",
    },
  },
  {
    files: ["src/js/**", "tests/playwright/**"],
    languageOptions: {
      globals: { ...globals.browser },
    },
    rules: {
      "no-console": "error",
    },
  },
];
