worker_processes auto;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {}

http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout;
    sendfile on;
    include /etc/nginx/conf.d/*.conf;
}
