[php]
; Buffer PHP output to reduce fragmented responses and improve compression.
output_buffering = 16384

[apcu]
apc.shm_size = "64M"

[opcache]
opcache.memory_consumption = 32
opcache.save_comments = 0
